name: firmware_updater
description: Firmware Updater
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_html: ^2.2.0
  flutter_localizations:
    sdk: flutter
  fwupd: ^0.2.0
  handy_window: ^0.1.2
  path: ^1.8.0
  provider: ^6.0.0
  yaru: ^0.2.1
  yaru_icons: ^0.1.2
  yaru_widgets: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
