name: firmware_updater
description: Firmware Updater
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^2.1.5
  fwupd:
    git:
      url: https://github.com/robert-ancell/fwupd.dart.git
      ref: unix-fd
  provider: ^6.0.0
  yaru: ^0.1.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
