name: firmware_notifier
description: A desktop notification service for fwupd.
publish_to: 'none'
environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.17.0
  desktop_notifications: ^0.6.3
  fwupd: ^0.2.2
  meta: ^1.8.0
  mockito: ^5.3.2
