name: firmware_notifier
description: A desktop notification service for fwupd.
publish_to: 'none'
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  dbus: ^0.7.8
  desktop_notifications: ^0.6.3
  fwupd: ^0.2.2
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  mockito: ^5.4.2
  test: ^1.16.0
  ubuntu_lints: ^0.4.0

