name: Generate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-runner:
    if: github.event_name != 'push'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos
    - run: melos pub get
    - run: flutter pub get # Bad state: Unable to generate package graph
    - run: melos run generate
    - run: ./.github/scripts/check-outdated-files.sh

  l10n:
    if: github.event_name != 'push'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos
    - run: melos pub get
    - run: melos run gen-l10n
    - run: ./.github/scripts/check-outdated-files.sh

  pull-request:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos
    - run: melos pub get
    - run: flutter pub get # Bad state: Unable to generate package graph
    - run: melos run generate
    - run: melos run gen-l10n
    - uses: peter-evans/create-pull-request@v5
      with:
        title: 'Regenerate files'
        commit-message: 'Regenerate files'